# Generated by Django 4.0.8 on 2022-11-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='newbalance.jpg', upload_to='uploads/')),
                ('studio_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='DateAdded')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='firstname',
            field=models.CharField(default='DEFAULT VALUE', max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(default='DEFAULT VALUE', max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='surname',
            field=models.CharField(default='DEFAULT VALUE', max_length=25),
        ),
    ]
