# Generated by Django 4.0.8 on 2022-11-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approve', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='green', max_length=6)),
            ],
        ),
    ]
