# Generated by Django 4.0.8 on 2022-11-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='type here', max_length=60),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Please upload image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='firstname',
            field=models.CharField(default='type here', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(default='type here', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.CharField(default='type here', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='type here', max_length=20),
        ),
    ]
