# Generated by Django 4.0.8 on 2022-11-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_cover_post_content_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_a',
            name='Approve',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=6),
        ),
    ]
