# Generated by Django 4.0.8 on 2022-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_a_comments_post_a_date_alter_post_a_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_a',
            name='Comments',
            field=models.CharField(default='.', max_length=50),
        ),
    ]
