# Generated by Django 4.0.8 on 2022-11-15 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_ied'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_a',
            name='Iedd',
            field=models.CharField(default=uuid.UUID('ded8ca84-6518-11ed-bf15-bce92f897dea'), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='Ied',
            field=models.CharField(default=uuid.UUID('ded8ca84-6518-11ed-bf15-bce92f897dea'), max_length=50),
        ),
    ]
