# Generated by Django 4.0.8 on 2022-11-15 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_a_iedd_alter_post_ied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Ied',
        ),
        migrations.RemoveField(
            model_name='post_a',
            name='Iedd',
        ),
        migrations.AddField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('f6fd3403-6526-11ed-a3ce-bce92f897dea'), max_length=50),
        ),
        migrations.AddField(
            model_name='post_a',
            name='idd',
            field=models.CharField(default='Clear and paste here', max_length=50),
        ),
    ]
