# Generated by Django 4.0.8 on 2022-11-15 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_ied_remove_post_a_iedd_post_idd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('fd561641-6527-11ed-b855-bce92f897dea'), max_length=50),
        ),
    ]
