# Generated by Django 4.0.8 on 2022-11-16 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('2b5872e4-65d5-11ed-a7d7-bce92f897dea'), max_length=50),
        ),
    ]
