# Generated by Django 4.0.8 on 2022-11-17 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approve',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('a231f69b-6656-11ed-8679-bce92f897dea'), max_length=50),
        ),
    ]
