# Generated by Django 4.0.8 on 2022-11-18 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_approve_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approve',
            field=models.CharField(default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('e3a6f3f4-6780-11ed-9f38-bce92f897dea'), max_length=50),
        ),
    ]
