# Generated by Django 4.0.8 on 2022-11-19 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_approve_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('fd49eb54-6805-11ed-8eb9-bce92f897dea'), max_length=50),
        ),
    ]
