# Generated by Django 4.0.8 on 2022-11-19 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('f297ff61-680b-11ed-82a1-bce92f897dea'), max_length=50),
        ),
    ]
