# Generated by Django 4.0.8 on 2022-11-19 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('ce4d20a6-6829-11ed-8db9-bce92f897dea'), max_length=50),
        ),
    ]
