# Generated by Django 4.0.8 on 2022-11-19 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('c5b2f235-6832-11ed-baea-bce92f897dea'), max_length=50),
        ),
    ]
