# Generated by Django 4.0.8 on 2022-11-19 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('1f1e01c4-6835-11ed-b8c6-bce92f897dea'), max_length=50),
        ),
    ]
