# Generated by Django 4.0.8 on 2022-11-19 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('65e3eefc-683d-11ed-ae57-bce92f897dea'), max_length=50),
        ),
    ]
