# Generated by Django 4.0.8 on 2022-11-25 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('cfedcc8e-6ca6-11ed-920b-bce92f897dea'), max_length=50),
        ),
    ]
