# Generated by Django 4.0.8 on 2022-11-25 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.TextField(default='Paste here', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('e8915a44-6ca6-11ed-8ad1-bce92f897dea'), max_length=50),
        ),
    ]
