# Generated by Django 4.0.8 on 2022-11-26 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_username_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approve',
            field=models.CharField(default='Pending', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('d62d8d66-6d47-11ed-a1ad-bce92f897dea'), max_length=50),
        ),
    ]
