# Generated by Django 4.0.8 on 2022-11-28 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('b990195d-6f00-11ed-8269-bce92f897dea'), max_length=50),
        ),
    ]
