# Generated by Django 4.0.8 on 2022-11-28 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('e7140993-6f17-11ed-8ddb-bce92f897dea'), max_length=50),
        ),
    ]
