# Generated by Django 4.0.8 on 2022-11-28 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('5e73c8b8-6f3c-11ed-a05a-bce92f897dea'), max_length=50),
        ),
    ]
