# Generated by Django 4.0.8 on 2022-11-28 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('b5afec41-6f5e-11ed-bec8-bce92f897dea'), max_length=50),
        ),
    ]
