# Generated by Django 4.0.8 on 2022-11-28 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('a26b60d6-6f5f-11ed-b45d-bce92f897dea'), max_length=50),
        ),
    ]
