# Generated by Django 4.0.8 on 2022-11-28 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('8718a373-6f61-11ed-b91f-bce92f897dea'), max_length=50),
        ),
    ]
