# Generated by Django 4.0.8 on 2022-11-28 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('5c7eb9db-6f62-11ed-8329-bce92f897dea'), max_length=50),
        ),
    ]
