# Generated by Django 4.0.8 on 2022-11-28 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('0c4a8001-6f63-11ed-ac52-bce92f897dea'), max_length=50),
        ),
    ]
