# Generated by Django 4.0.8 on 2022-11-28 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('d976181d-6f63-11ed-b652-bce92f897dea'), max_length=50),
        ),
    ]
