# Generated by Django 4.0.8 on 2022-11-28 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('ac95f26d-6f64-11ed-b57f-bce92f897dea'), max_length=50),
        ),
    ]
