# Generated by Django 4.0.8 on 2022-11-28 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('f56143e5-6f64-11ed-80ab-bce92f897dea'), max_length=50),
        ),
    ]
