# Generated by Django 4.0.8 on 2022-11-28 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('404aa488-6f65-11ed-966c-bce92f897dea'), max_length=50),
        ),
    ]
