# Generated by Django 4.0.8 on 2022-11-28 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('43b23d9e-6f67-11ed-9aab-bce92f897dea'), max_length=50),
        ),
    ]
