# Generated by Django 4.0.8 on 2022-11-28 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('cc2a38a6-6f68-11ed-a377-bce92f897dea'), max_length=50),
        ),
    ]
