# Generated by Django 4.0.8 on 2022-11-28 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('6ab52053-6f69-11ed-9a8a-bce92f897dea'), max_length=50),
        ),
    ]
