# Generated by Django 4.0.8 on 2022-11-28 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('a3e18cb6-6f6a-11ed-9e9f-bce92f897dea'), max_length=50),
        ),
    ]
