# Generated by Django 4.0.8 on 2022-11-28 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('dfeef336-6f6a-11ed-885d-bce92f897dea'), max_length=50),
        ),
    ]
