# Generated by Django 4.0.8 on 2022-11-28 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('1ca6edcc-6f6c-11ed-a371-bce92f897dea'), max_length=50),
        ),
    ]
