# Generated by Django 4.0.8 on 2022-11-28 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('0d4e5410-6f6d-11ed-a377-bce92f897dea'), max_length=50),
        ),
    ]
