# Generated by Django 4.0.8 on 2022-11-28 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('c8306eaf-6f6d-11ed-9792-bce92f897dea'), max_length=50),
        ),
    ]
