# Generated by Django 4.0.8 on 2022-11-28 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('bd9b904c-6f6e-11ed-9d92-bce92f897dea'), max_length=50),
        ),
    ]
