# Generated by Django 4.0.8 on 2022-11-28 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('70688d15-6f6f-11ed-8cdc-bce92f897dea'), max_length=50),
        ),
    ]
