# Generated by Django 4.0.8 on 2022-11-28 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('22d6cb22-6f71-11ed-be9a-bce92f897dea'), max_length=50),
        ),
    ]
