# Generated by Django 4.0.8 on 2022-11-30 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('175420a7-70a6-11ed-9d5b-bce92f897dea'), max_length=50),
        ),
    ]
