# Generated by Django 4.0.8 on 2022-11-30 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0063_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('b9ed67da-70fe-11ed-a212-bce92f897dea'), max_length=50),
        ),
    ]
