# Generated by Django 4.0.8 on 2022-12-01 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('a8b89213-7164-11ed-84ef-bce92f897dea'), max_length=50),
        ),
    ]
