# Generated by Django 4.0.8 on 2022-12-01 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0067_alter_post_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idd',
            field=models.CharField(default=uuid.UUID('111f9b28-7166-11ed-9bb6-bce92f897dea'), max_length=50),
        ),
    ]
