# Generated by Django 4.0.8 on 2022-11-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approve', models.CharField(default='DEFAULT VALUE', max_length=25)),
            ],
        ),
    ]
