# Generated by Django 4.0.8 on 2022-11-28 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('approve', '0004_post_comments_alter_post_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Paste your username here', max_length=15)),
                ('title', models.CharField(default='Type here', max_length=25)),
                ('eventdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approve', models.CharField(default='Pending', max_length=10)),
            ],
        ),
    ]
