# Generated by Django 4.0.8 on 2022-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve', '0006_cals_eventtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cals',
            name='act',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
