# Generated by Django 4.1.3 on 2022-11-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_post_cover_remove_post_date_remove_post_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.TextField(default='Message..........', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(default='Enter your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='firstname',
            field=models.CharField(default='Enter your Firstname', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.CharField(default='Enter your Surname', max_length=25),
        ),
    ]
