# Generated by Django 4.1.3 on 2022-11-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post_message_alter_post_email_alter_post_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(default='Message..........', max_length=50),
        ),
    ]
